th2-net/th2-rpt-viewer

- src/components/notifications/FetchError.tsx
- src/components/search-panel/SearchPanel.tsx
- src/components/search-panel/SearchPanelForm.tsx
- src/stores/NotificationsStore.ts
- src/stores/SearchStore.ts
- src/styles/action.scss
- src/styles/bookmarks.scss
- src/styles/common/_mixins.scss
- src/styles/events.scss
- src/styles/toast-content.scss
* autocomplete list for sessions
* toast messages for sse errors
* text-overflow mixin
> search-panel-improvements.

- package.json
- src/components/BookmarksPanel.tsx
- src/components/event/flat-event-list/DetailedFlatEventCard.tsx
- src/components/graph/GraphChunksVirtualizer.tsx
- src/components/graph/OutsideItems.tsx
- src/components/message/message-card-list/MessagesScrollContainer.tsx
- src/components/search-panel/SearchPanel.tsx
- src/components/workspace/Workspace.tsx
- src/components/workspace/WorkspacesLayout.tsx
- src/stores/FilterStore.ts
- src/stores/SearchStore.ts
- src/stores/messages/MessageUpdateStore.ts
- src/stores/messages/MessagesDataProviderStore.ts
- src/stores/messages/MessagesStore.ts
- src/stores/messages/SSEChannel.ts
- src/stores/workspace/TabsStore.ts
- src/styles/bookmarks.scss
- src/styles/search-panel.scss
- Move sessions fetching into SearchStore
- Fix search input styles and linting
- Allow closing all workspaces except SearchWorkspace
- Close sse connection after completing messages fetching
> Sessions fetching optimization and styles fixes

- package.json
- src/components/workspace/WorkspaceSplitter.tsx
- src/styles/root.scss
- src/styles/search-panel.scss
- src/styles/tabs.scss
- src/styles/workspace.scss
* Enable tabs scrolling
* Prevent text selection on panel resize
> Improve styles

- package.json
- src/api/sse.ts
- src/stores/SearchStore.ts
- src/styles/search-panel.scss
* search progress bar displays "keep_alive" event's timestamps
> search-progress-sse-heartbeat-visualization.

- package-lock.json
- package.json
- src/components/BookmarksPanel.tsx
- src/components/event/EventCardHeader.tsx
- src/components/event/EventDetailInfoCard.tsx
- src/components/event/tree/EventTreeList.tsx
- src/components/graph/GraphItemsMenu.tsx
- src/components/graph/OutsideItems.tsx
- src/components/graph/search/GraphSearchDialog.tsx
- src/components/message/MessagesWindow.tsx
- src/components/message/MessagesWindowHeader.tsx
- src/components/message/message-card-list/MessagesVirtualizedList.tsx
- src/components/message/message-card/MessageCard.tsx
- src/helpers/date.ts
- src/helpers/event.ts
- src/helpers/graph.ts
- src/helpers/message.ts
- src/hooks/useMessagesDataStore.ts
- src/stores/SearchStore.ts
- src/stores/events/EventsStore.ts
- src/stores/messages/MessagesDataProviderStore.ts
- src/stores/messages/MessagesFilterStore.ts
- src/stores/messages/MessagesStore.ts
- src/stores/messages/SSEChannel.ts
- src/stores/workspace/SearchWorkspaceStore.ts
- Fix messages loading bug on long response
- Refactor messages store
- Add timestamp resolver helper function
- Update virtuoso
> Fix messages loading bug on long response & refactor messages store

- package-lock.json
- package.json
- src/components/search-panel/SearchPanel.tsx
- src/components/search-panel/SearchPanelResults.tsx
- src/components/search-panel/SearchResultGroup.tsx
- src/stores/workspace/SearchWorkspaceStore.ts
- src/stores/workspace/WorkspacesStore.ts
Click on search group should open workspace using intermediate group time
> Search group following

- src/components/message/message-card/MessageCard.tsx
- src/styles/messages.scss
* message card tools replacement
> TH2-1628. Render messages in ascii and json mode as a single line

- .eslintrc.js
- package.json
- src/api/ApiSchema.ts
- src/api/message.ts
- src/components/filter/FilterPanel.tsx
- src/components/filter/MessagesFilterPanel.tsx
- src/components/message/message-card-list/MessagesVirtualizedList.tsx
- src/components/message/message-card/MessageCard.tsx
- src/stores/messages/MessagesDataProviderStore.ts
- src/stores/messages/MessagesFilterStore.ts
- src/stores/messages/MessagesSSELoader.ts
- src/stores/workspace/WorkspacesStore.ts
* Soft filter is now being matched through individual api request for each message
* Fix isSoftFilter applied set to true even if there are no filters applied
> Messages soft filter improvements

- package.json
- src/components/bookmarks/BookmarksPanel.tsx
- src/components/event/EventCardHeader.tsx
- src/components/graph/Graph.tsx
- src/components/graph/search/GraphSearch.tsx
- src/components/graph/search/GraphSearchInput.tsx
- src/components/message/message-card/MessageCard.tsx
- src/stores/GraphStore.ts
- src/stores/events/EventsDataStore.ts
- src/stores/events/EventsStore.ts
- src/stores/messages/MessagesStore.ts
- src/styles/events.scss
- src/styles/messages.scss
* Show hovered item on graph on item timestamp hover
* Increase debounce ms
* Restore graph timestamp after reseting hovered item
> Improve graph hovered item display

- src/components/bookmarks/BookmarksPanel.tsx
- src/components/workspace/SearchWorkspace.tsx
- src/components/workspace/WorkspaceSplitter.tsx
- src/stores/SearchStore.ts
- Fix search panel layout changes after toggling bookmark on search result
- Fix search saves searches with empty results
- Show selected bookmarks counter
> Minor bug fixes and improvements

- src/components/embedded/EmbeddedApp.tsx
- src/components/embedded/EmbeddedEvent.tsx
- src/components/embedded/EmbeddedEventHeader.tsx
- src/components/embedded/EmbeddedMessage.tsx
- src/styles/embedded.scss
> TH2-2242. Event header is missing in embedded view

- package.json
- src/components/filter/EventsFilterPanel.tsx
- src/components/filter/MessagesFilterPanel.tsx
- src/components/filter/row/EventResolverRow.tsx
- src/components/filter/row/MultipleStringFIlterRow.tsx
- src/components/filter/row/StringRow.tsx
- src/components/search-panel/SearchPanelFilters.tsx
- src/components/search-panel/SearchPanelForm.tsx
- src/helpers/search.ts
- src/models/filter/FilterInputs.ts
- src/styles/search-panel.scss
> TH2-2183. Add hints to explain Search - Parent Event field work

- package.json
- src/styles/bookmarks.scss
> TH2-1868. Bookmarks' scrollbar doesn't appear when there are one or two extra bookmarks in list

- package.json
- src/stores/events/EventsDataStore.ts
> TH2-2281. 'Something went wrong' while click on event timeline

- package.json
- src/components/filter/MessagesFilterPanel.tsx
- src/components/message/MessageReplayModal.tsx
- src/components/search-panel/SearchPanelFilters.tsx
> TH2-2313.  Critical error "Cannot read property 'negative' of undefined" after opening a saved report

- package.json
- src/components/search-panel/SearchPanelForm.tsx
Invalid messages are marked as invalid. Search is highlighted in red only if invalid messages are entered
> Fix message search

- package.json
- src/components/util/Bubble.tsx
> TH2-2225. It is not possible to move a caret with the mouse while you are editing submitter session name in the filter

- package-lock.json
- package.json
- src/styles/messages.scss
Fix message tooltip width, so it doesn't change layout on hover
> Fix hovering message changes layout

- package.json
- src/components/embedded/embedded-stores/EmbeddedMessagesDataProviderStore.tsx
- src/components/message/message-card-list/MessagesCardList.tsx
- src/stores/SSEChannel/MessagesSSEChannel.ts
- src/stores/messages/MessagesDataProviderStore.ts
- Make `initialResponseTimeoutMs` optional
- Display loading anchor message status
> Fix anchor message loading

- src/components/message/AttachedMessagesSelection.tsx
- src/components/message/message-card/MessageCard.tsx
- src/components/util/StateSaver.tsx
- Fix previous selected message still highlights after selecting another message
- Fix attached messages selection
- Fix StateSaver update callback is missing key dependency
> Fix attached messages selection and message highlighting

- package.json
- src/components/message/message-card/MessageCard.tsx
- src/components/message/message-card/MessageCardBase.tsx
- src/stores/messages/MessagesDataProviderStore.ts
- src/stores/messages/MessagesStore.ts
- Fix sometimes attached message is out of visible range
- Fix warning \<pre\> can not be descendant of \<p\>
> TH2-2917. Fix sometimes attached message is out of visible range

- package.json
- src/components/message/message-card/MessageCard.tsx
- src/hooks/index.ts
- src/hooks/useMessagesViewTypesStore.ts
- src/stores/messages/MessagesStore.ts
- src/stores/messages/MessagesViewTypesStore.ts
- src/stores/messages/SavedMessageViewType.ts
- src/stores/workspace/WorkspaceStore.ts
- src/stores/workspace/WorkspacesStore.ts
> TH2-2461. Make the messages list to react when display mode changes.

- package.json
- src/components/message/message-card/MessageCardTools.tsx
> TH2-3021. [ReportViewerUI] 'Copy full/Copy simplified' buttons disappear from panel

- package-lock.json
- package.json
- src/components/embedded/EmbeddedMessagesFilterPanel.tsx
- src/components/embedded/embedded-stores/EmbeddedMessagesDataProviderStore.tsx
- src/components/embedded/embedded-stores/EmbeddedMessagesStore.tsx
- src/components/filter/EventsFilterPanel.tsx
- src/components/filter/FilterPanel.tsx
- src/components/filter/MessageFilterSessionFilter.tsx
- src/components/filter/MessagesFilterPanel.tsx
- src/stores/messages/MessagesDataProviderStore.ts
- src/stores/messages/MessagesStore.ts
- src/stores/workspace/WorkspaceStore.ts
- src/styles/messages.scss
Added stop message loading button
Removed loading spinner from filters button in filters panel
> TH2-3008: Stop message loading button

- package-lock.json
- package.json
* fixed by react-virtuoso upgrade
> TH2-3169 [rpt-data-viewer] Event tab is empty

- package.json
- src/components/bookmarks/BookmarksPanel.tsx
> TH2-3701. Bookmarks Seacrh Works Incorrectly with uppercase and lower case

- package-lock.json
- package.json
- src/components/search-panel/SearchPanelForm.tsx
- src/stores/SearchStore.ts
* filters are uneditable while search is in progress
> TH2-3719. Search results are not cleared, after changing passed/failed status

- package.json
- src/components/workspace/SearchWorkspace.tsx
Number of marked bookmarks reset after searching
> [TH2-3846] Reset number of marked bookmarks

- package.json
- resources/icons/graph-arrow-left-disabled.svg
- src/components/search-panel/SearchPanel.tsx
- src/components/search-panel/SearchPanelResults.tsx
- src/styles/search-panel.scss
To prevent misunderstanding in the future, added counter of results and disabled icons for nav arrows
> [TH2-4140] "x" button in event search works incorrectly

- src/components/notifications/FetchErrorToast.tsx
- src/components/notifications/GenericErrorToast.tsx
- src/components/notifications/UrlErrorToast.tsx
- src/helpers/fetchRetry.ts
- src/stores/BookmarksStore.ts
- src/stores/MessageBodySortStore.ts
- src/stores/MessageDisplayRulesStore.ts
- src/stores/NotificationsStore.ts
- src/stores/RootStore.ts
- src/stores/SearchStore.ts
- src/stores/events/EventsDataStore.ts
- src/stores/messages/MessagesDataProviderStore.ts
improve error toasts. Add copy button where it is not present
> [TH2-4337] Text of some errors can't be copied

- src/components/message/message-card/MessageHeader.tsx
Incorrect hover text for message type in messages list
> [TH2-4339] Incorrect hover text for message type in messages list
